### PR TITLE
feat: forward authorization messages

### PR DESCRIPTION
**Pull request by DonChangfoot**
* GET authorization requests
* PUT authorization responses
* PUT authorization errors

### CODE REVIEW

**Comment by lewisdaly** [comment]
@DonChangfoot, I just noticed this here - feel free to assign a few people to review when it's ready to go.

**Comment by lewisdaly** [comment]
@elnyry was there a reason for closing this?

**Comment by elnyry** [comment]
> @elnyry was there a reason for closing this?

Nope, mistakenly moved..

**Comment by DonChangfoot** [comment]
Closing to test repo settings.

**Pull request closed without merging**
